import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Bell,
  Bold,
  Box,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleCheck,
  CirclePlus,
  CircleX,
  Clock,
  Code,
  Command,
  CreditCard,
  Crown,
  Dot,
  Edit,
  ExternalLink,
  EyeOff,
  File,
  FileText,
  FileType,
  FileSpreadsheet,
  FolderArchive,
  Folder,
  GripVertical,
  HelpCircle,
  Info,
  Italic,
  LayoutDashboard,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  MessageCircle,
  Minus,
  Moon,
  Music,
  Palette,
  Paperclip,
  Phone,
  Image,
  Pizza,
  Plus,
  type LucideIcon,
  Search,
  ChevronsUpDown,
  Send,
  Settings,
  Share,
  Slash,
  Sparkles,
  Star,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  Type,
  Underline,
  Upload,
  User,
  UserCircle,
  UserPen,
  UserX,
  Users,
  Video,
  X
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  // General
  alertCircle: AlertCircle,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  check: Check,
  checks: CheckCheck,
  circleCheck: CircleCheck,
  close: X,
  clock: Clock,
  code: Code,
  dots: Dot,
  ellipsis: MoreHorizontal,
  externalLink: ExternalLink,
  help: HelpCircle,
  info: Info,
  spinner: Loader2,
  search: Search,
  settings: Settings,
  trash: Trash2,

  // Navigation / Chevrons
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUpDown: ChevronsUpDown,

  // Layout
  dashboard: LayoutDashboard,
  // kanban: LayoutKanban,
  // panelLeft: LayoutSidebar,

  // User
  user: User,
  user2: UserCircle,
  account: UserCircle,
  profile: User,
  employee: UserX,
  userPen: UserPen,
  teams: Users,

  // Brand
  // github: BrandGithub,
  // twitter: BrandTwitter,
  logo: Command,

  // Communication
  chat: MessageCircle,
  notification: Bell,
  phone: Phone,
  video: Video,
  send: Send,
  paperclip: Paperclip,

  // Files
  page: File,
  post: FileText,
  // fileTypePdf: FilePdf,
  fileTypeDoc: FileType,
  fileTypeXls: FileSpreadsheet,
  fileZip: FolderArchive,
  media: Image,
  music: Music,

  // Actions
  add: Plus,
  edit: Edit,
  upload: Upload,
  share: Share,
  login: LogIn,
  logout: LogOut,
  gripVertical: GripVertical,

  // Shapes / Indicators
  circle: Circle,
  circleX: CircleX,
  plusCircle: CirclePlus,
  xCircle: CircleX,
  minus: Minus,

  // Theme
  sun: Sun,
  moon: Moon,
  // brightness: Brightness,
  laptop: Laptop,
  palette: Palette,

  // Commerce / Plans
  billing: CreditCard,
  creditCard: CreditCard,
  product: Box,
  pro: Crown,
  exclusive: Star,
  sparkles: Sparkles,
  badgeCheck: Verified,
  lock: Lock,

  // Data / Charts
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  eyeOff: EyeOff,
  // adjustments: AdjustmentsHorizontal,

  // Text formatting
  bold: Bold,
  italic: Italic,
  underline: Underline,
  text: Type,

  // Toast
  toastSuccess: CircleCheck,
  toastInfo: Info,
  toastWarning: AlertTriangle,
  toastError: CircleX,
  toastLoading: Loader2,

  // Misc
  pizza: Pizza,
  workspace: Folder,
  // forms: ClipboardText,
  slash: Slash,
  calendar: Calendar,
  // galleryVerticalEnd: Stack,
  moreHorizontal: MoreHorizontal
};

// You'll also need to import MoreHorizontal and Laptop since they weren't in the original list
import { MoreHorizontal, Laptop, Verified } from 'lucide-react';